<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/admin/Site.Master" AutoEventWireup="true" CodeBehind="SanPhamNhom.aspx.cs" Inherits="QLBH.admin.SanPhamNhom" %>


<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">






    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="MaNhomSP" DataSourceID="EntityDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CssClass="table table-striped">
        <Columns>
            <asp:BoundField DataField="MaNhomSP" HeaderText="MaNhomSP" ReadOnly="True" SortExpression="MaNhomSP" />
            <asp:BoundField DataField="TenNhomSP" HeaderText="TenNhomSP" SortExpression="TenNhomSP" />
        </Columns>
    </asp:GridView>
    <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateInsertButton="True" AutoGenerateRows="False" DataKeyNames="MaNhomSP" DataSourceID="EntityDataSource1" DefaultMode="Insert" Height="50px" Width="158px" OnItemInserted="DetailsView1_ItemInserted">
        <Fields>
            <asp:BoundField DataField="MaNhomSP" InsertVisible="False" HeaderText="MaNhomSP" ReadOnly="True" SortExpression="MaNhomSP" />
            <asp:BoundField DataField="TenNhomSP" HeaderText="TenNhomSP" SortExpression="TenNhomSP" />
        </Fields>
    </asp:DetailsView>
    <asp:EntityDataSource ID="EntityDataSource1" runat="server" ConnectionString="name=QLBHDBContext" DefaultContainerName="QLBHDBContext" EnableFlattening="False" EntitySetName="SPNhoms" Include="SPLoais" EnableInsert="True" EnableUpdate="True" EnableDelete="True">
    </asp:EntityDataSource>






</asp:Content>
