//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int MaGioHang { get; set; }
        public Nullable<int> MaSp { get; set; }
        public Nullable<int> MaKh { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string DiaChiIp { get; set; }
    
        public virtual Kh Kh { get; set; }
        public virtual Sp Sp { get; set; }
    }
}
