//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sp()
        {
            this.GioHangs = new HashSet<GioHang>();
            this.PhieuGiaoChiTiets = new HashSet<PhieuGiaoChiTiet>();
            this.PhieuHdChiTiets = new HashSet<PhieuHdChiTiet>();
            this.PhieuNhapChiTiets = new HashSet<PhieuNhapChiTiet>();
        }
    
        public int MaSp { get; set; }
        public Nullable<int> MaLoaiSp { get; set; }
        public Nullable<int> MaNcc { get; set; }
        public string TenSp { get; set; }
        public string HinhSp { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> SoLuongTonKho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual Ncc Ncc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuGiaoChiTiet> PhieuGiaoChiTiets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuHdChiTiet> PhieuHdChiTiets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapChiTiet> PhieuNhapChiTiets { get; set; }
        public virtual SpLoai SpLoai { get; set; }
    }
}
